language: cpp
compiler:
- gcc
before_install:
- sudo apt-get update
- sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-serialization-dev
- git clone https://github.com/proycon/colibri-core
- cd colibri-core
- bash bootstrap
- ./configure
- make
- sudo make install
- cd ..
install:
  - cd hpyplm && g++ -std=c++0x -nostartfiles -DkORDER='3' -g -O3 -I.. -o hpyplm_train3 -lcolibricore -lboost_filesystem -lboost_system -lboost_serialization -lbz2
